from pathlib import Path
import cv2


class FaceEncoder:
    def __init__(self):
        # Find the root folder of the project
        project_root = Path(__file__).resolve().parent.parent.parent

        # Location of the SFace model
        model_path = (
            project_root
            / "models"
            / "sface"
            / "face_recognition_sface_2021dec.onnx"
        )

        # Make sure the model exists
        if not model_path.exists():
            raise FileNotFoundError(
                f"SFace model not found: {model_path}"
            )

        # Load SFace
        self.recognizer = cv2.FaceRecognizerSF.create(
            str(model_path),
            ""
        )

    def encode(self, image, face):
        """
        Align a detected face and generate its SFace embedding.

        Args:
            image: Original OpenCV image.
            face: One face returned by YuNet.

        Returns:
            Face embedding generated by SFace.
        """

        # Align and crop the face
        aligned_face = self.recognizer.alignCrop(
            image,
            face
        )

        # Generate the face embedding
        embedding = self.recognizer.feature(
            aligned_face
        )

        return embedding